const std = @import("std");
const assert = std.debug.assert;

const helpers = @import("helpers.zig");
const t = @import("unicode_types.zig");
const u = @import("unicode_info.zig");
const UnicodeInfo = u.UnicodeInfo;
const Data = u.Data;
const parser = @import("parser.zig");
const export_types = @import("export/types.zig");
const GraphemeBoundryClass = export_types.GraphemeBoundryClass;
const GraphemeBreakState = export_types.GraphemeBreakState;
const GraphemeBreakTestResult = export_types.GraphemeBreakTestResult;
const GraphemeBreakCombination = export_types.GraphemeBreakCombination;

const generatePropertyLookupTable = @import("property_table_generator.zig").generatePropertyLookupTable;

pub fn main(init: std.process.Init.Minimal) !void {
    var start = std.time.Timer.start() catch unreachable;
    var threaded = std.Io.Threaded.init(std.heap.page_allocator, .{ .environ = init.environ });
    const io = threaded.io();

    const info = try UnicodeInfo.init(std.heap.page_allocator);
    const times = try parser.parseUCDFiles(io, info);

    try std.Io.Dir.cwd().copyFile("src/tools/export/types.zig", std.Io.Dir.cwd(), "src/unicode/types.zig", io, .{});
    try std.Io.Dir.cwd().copyFile("src/tools/export/root.zig", std.Io.Dir.cwd(), "src/unicode/root.zig", io, .{});
    try std.Io.Dir.cwd().copyFile("src/tools/export/utf8.zig", std.Io.Dir.cwd(), "src/unicode/utf8.zig", io, .{});

    const table_time = try generatePropertyLookupTable(io, std.heap.page_allocator, "src/unicode/properties.zig", info);
    const grapheme_time = try generateGraphemeBreakLookupTable(io, std.heap.page_allocator, "src/unicode/grapheme_break.zig");

    var buffer: [4096]u8 = undefined;
    var stdout = std.Io.File.stdout().writer(io, &buffer);
    try stdout.interface.print("Total Time to: {d}ms\n", .{@as(f32, @floatFromInt(start.read())) / std.time.ns_per_ms});
    try stdout.interface.print("    parseGeneralCategory: {d}ms\n", .{@as(f32, @floatFromInt(times.general_category)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseDerivedCoreProperties: {d}ms\n", .{@as(f32, @floatFromInt(times.derived_core_properties)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseGraphemeBreakProperty: {d}ms\n", .{@as(f32, @floatFromInt(times.grapheme_break)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseEastAsianWidth: {d}ms\n", .{@as(f32, @floatFromInt(times.east_asian_width)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseEmoji: {d}ms\n\n", .{@as(f32, @floatFromInt(times.emoji)) / std.time.ns_per_ms});
    try stdout.interface.print("    Property Table Generation Time: {d}ms\n", .{@as(f32, @floatFromInt(table_time)) / std.time.ns_per_ms});
    try stdout.interface.print("    GraphemeBreak Table Generation Time: {d}ms\n", .{@as(f32, @floatFromInt(grapheme_time)) / std.time.ns_per_ms});
    try stdout.interface.flush();
}

// Reference:
// https://github.com/ghostty-org/ghostty/blob/2fd3efd6cdf0629f57572af58dff0ae9115ce919/src/unicode/grapheme.zig
// https://mitchellh.com/writing/ghostty-devlog-006
pub fn generateGraphemeBreakLookupTable(
    io: std.Io,
    allocator: std.mem.Allocator,
    file_path: []const u8,
) !u64 {
    const grapheme_file = try std.Io.Dir.cwd().createFile(io, file_path, .{});
    defer grapheme_file.close(io);

    var grapheme_file_buffer: [4096]u8 = undefined;
    var grapheme_file_writer = grapheme_file.writer(io, &grapheme_file_buffer);
    const writer = &grapheme_file_writer.interface;
    var start = std.time.Timer.start() catch unreachable;

    const results: []GraphemeBreakTestResult = try allocator.alloc(GraphemeBreakTestResult, std.math.maxInt(u10));
    defer allocator.free(results);

    const classes = comptime std.meta.fields(GraphemeBoundryClass);
    for (0..std.math.maxInt(u2) + 1) |initial_state| {
        inline for (classes) |gbc1| {
            inline for (classes) |gbc2| {
                var state: GraphemeBreakState = @bitCast(@as(u2, @intCast(initial_state)));
                const combination: GraphemeBreakCombination = .{
                    .state = state,
                    .gbc1 = @field(GraphemeBoundryClass, gbc1.name),
                    .gbc2 = @field(GraphemeBoundryClass, gbc2.name),
                };
                const result = isGraphemeBreak(combination.gbc1, combination.gbc2, &state);
                results[combination.asUsize()] = .{
                    .is_break = result,
                    .state = combination.state,
                };
            }
        }
    }

    try writer.print(
        \\//! DO NOT EDIT - This file is auto-generated by generate_lookup_tables.zig
        \\//!
        \\//! This file contains the lookup tables for the unicode grapheme break.
        \\
        \\const std = @import("std");
        \\
        \\const t = @import("types.zig");
        \\const GraphemeBreakTestResult = t.GraphemeBreakTestResult;
        \\const GraphemeBreakCombination = t.GraphemeBreakCombination;
        \\const GraphemeBreakState = t.GraphemeBreakState;
        \\const getProperty = @import("properties.zig").getProperty;
        \\
        \\pub fn graphemeBreak(prev_cp: u21, next_cp: u21, state: *GraphemeBreakState) bool {{
        \\    const result = break_table[
        \\        (GraphemeBreakCombination{{
        \\            .state = state.*,
        \\            .gbc1 = getProperty(prev_cp).grapheme_boundary_class,
        \\            .gbc2 = getProperty(next_cp).grapheme_boundary_class,
        \\        }}).asUsize()
        \\    ];
        \\    state.* = result.state;
        \\    return result.is_break;
        \\}}
        \\
        \\const break_table: [{d}]GraphemeBreakTestResult align(std.atomic.cache_line) = .{{
        \\
    , .{results.len});

    for (results, 0..) |result, i| {
        const key: GraphemeBreakCombination = @bitCast(@as(u10, @intCast(i)));
        try writer.print("    .{{ .is_break = {any}, .state = .{{ .extended_pictographic = {any}, .regional_indicator = {any} }} }}, // {s} -> {s} state:[extended_pict = {any}, regiona_indicator = {any}]\n", .{
            result.is_break,
            result.state.extended_pictographic,
            result.state.regional_indicator,
            if (@intFromEnum(key.gbc1) < 14) @tagName(key.gbc1) else "Invalid",
            if (@intFromEnum(key.gbc2) < 14) @tagName(key.gbc2) else "Invalid",
            key.state.extended_pictographic,
            key.state.regional_indicator,
        });
    }

    try writer.writeAll("};\n\n");
    try writer.flush();

    return start.read();
}

// GB1 and GB2 are to be handled by the iterator
// GB3, GB4, and GB5 are to be handled by the caller. They must filter out the control characters.
// https://www.unicode.org/reports/tr29/
fn isGraphemeBreak(gbc1: GraphemeBoundryClass, gbc2: GraphemeBoundryClass, state: *GraphemeBreakState) bool {
    // GB11
    if (!state.extended_pictographic and gbc1.isExtendedPictographic()) {
        state.extended_pictographic = true;
    }

    // GB6 L×(L | V | LV | LVT)
    // GB7 (LV | V) × (V | T)
    // GB8 (LVT | T) × T
    switch (gbc1) {
        .L => switch (gbc2) {
            .L, .V, .LV, .LVT => return true,
            else => {},
        },
        .LV, .V => switch (gbc2) {
            .V, .T => return true,
            else => {},
        },
        .LVT, .T => switch (gbc2) {
            .T => return true,
            else => {},
        },
        else => {},
    }
    // GB9 x (Extend | ZWJ)
    if (gbc2 == .extend or gbc2 == .zwj) return false;
    // GB9a x SpacingMark
    if (gbc2 == .spacing_mark) return false;
    // GB9b Prepend x
    if (gbc1 == .prepend) return false;

    // GB12, GB13: Do not break within emoji flag sequences. That is, do not break between regional indicator (RI)
    // symbols if there is an odd number of RI characters before the break point.
    if (gbc1 == .regional_indicator and gbc2 == .regional_indicator) {
        if (state.regional_indicator) {
            state.regional_indicator = false;
            return true;
        } else {
            state.regional_indicator = true;
            return false;
        }
    }

    if (state.extended_pictographic and gbc1 == .zwj and gbc2.isExtendedPictographic()) {
        state.extended_pictographic = false;
        return false;
    }

    // https://github.com/ghostty-org/ghostty/blob/2fd3efd6cdf0629f57572af58dff0ae9115ce919/src/unicode/grapheme.zig#L139
    if (gbc2 == .emoji_modifier and gbc1 == .extended_pictographic_base) {
        return false;
    }

    return true;
}
