const std = @import("std");
const assert = std.debug.assert;

const helpers = @import("helpers.zig");
const t = @import("unicode_types.zig");
const u = @import("unicode_info.zig");
const UnicodeInfo = u.UnicodeInfo;
const Data = u.Data;
const parser = @import("parser.zig");
const export_types = @import("export/types.zig");
const GraphemeBoundryClass = export_types.GraphemeBoundryClass;
const GraphemeBreakState = export_types.GraphemeBreakState;
const GraphemeBreakTestResult = export_types.GraphemeBreakTestResult;
const GraphemeBreakCombination = export_types.GraphemeBreakCombination;

const generatePropertyLookupTable3Stage = @import("property_table_generator.zig").generatePropertyLookupTable3Stage;
const generatePropertyLookupTable2Stage = @import("property_table_generator.zig").generatePropertyLookupTable2Stage;

pub fn main(init: std.process.Init.Minimal) !void {
    var start = std.time.Timer.start() catch unreachable;
    var threaded = std.Io.Threaded.init(std.heap.page_allocator, .{ .environ = init.environ });
    const io = threaded.io();

    const info = try UnicodeInfo.init(std.heap.page_allocator);
    const times = try parser.parseUCDFiles(io, info);

    try std.Io.Dir.cwd().copyFile("tools/export/types.zig", std.Io.Dir.cwd(), "src/unicode/types.zig", io, .{});
    try std.Io.Dir.cwd().copyFile("tools/export/root.zig", std.Io.Dir.cwd(), "src/unicode/root.zig", io, .{});
    try std.Io.Dir.cwd().copyFile("tools/export/UTF8Decoder.zig", std.Io.Dir.cwd(), "src/unicode/UTF8Decoder.zig", io, .{});
    try std.Io.Dir.cwd().copyFile("tools/export/GraphemeIterator.zig", std.Io.Dir.cwd(), "src/unicode/GraphemeIterator.zig", io, .{});

    // NOTE(adi): 2-stage lookup table is faster than 3-stage lookup table for now
    const two_stage_table_time = try generatePropertyLookupTable2Stage(io, std.heap.page_allocator, "src/unicode/properties.zig", info);
    // const three_stage_table_time = try generatePropertyLookupTable3Stage(io, std.heap.page_allocator, "src/unicode/properties.zig", info);
    const grapheme_time = try generateGraphemeBreakLookupTable(io, std.heap.page_allocator, "src/unicode/grapheme_break.zig");

    var buffer: [4096]u8 = undefined;
    var stdout = std.Io.File.stdout().writer(io, &buffer);
    try stdout.interface.print("Total Time to: {d}ms\n", .{@as(f32, @floatFromInt(start.read())) / std.time.ns_per_ms});
    try stdout.interface.print("    parseGeneralCategory: {d}ms\n", .{@as(f32, @floatFromInt(times.general_category)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseDerivedCoreProperties: {d}ms\n", .{@as(f32, @floatFromInt(times.derived_core_properties)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseGraphemeBreakProperty: {d}ms\n", .{@as(f32, @floatFromInt(times.grapheme_break)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseEastAsianWidth: {d}ms\n", .{@as(f32, @floatFromInt(times.east_asian_width)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseEmoji: {d}ms\n", .{@as(f32, @floatFromInt(times.emoji)) / std.time.ns_per_ms});
    try stdout.interface.print("    parseEmojiVS: {d}ms\n\n", .{@as(f32, @floatFromInt(times.emoji_vs)) / std.time.ns_per_ms});
    // try stdout.interface.print("    Property Table 3Stage Generation Time: {d}ms\n", .{@as(f32, @floatFromInt(three_stage_table_time)) / std.time.ns_per_ms});
    try stdout.interface.print("    Property Table 2Stage Generation Time: {d}ms\n", .{@as(f32, @floatFromInt(two_stage_table_time)) / std.time.ns_per_ms});
    try stdout.interface.print("    GraphemeBreak Table Generation Time: {d}ms\n", .{@as(f32, @floatFromInt(grapheme_time)) / std.time.ns_per_ms});
    try stdout.interface.flush();
}

// Reference:
// https://github.com/ghostty-org/ghostty/blob/2fd3efd6cdf0629f57572af58dff0ae9115ce919/src/unicode/grapheme.zig
// https://mitchellh.com/writing/ghostty-devlog-006
pub fn generateGraphemeBreakLookupTable(
    io: std.Io,
    _: std.mem.Allocator,
    file_path: []const u8,
) !u64 {
    const grapheme_file = try std.Io.Dir.cwd().createFile(io, file_path, .{});
    defer grapheme_file.close(io);

    var grapheme_file_buffer: [4096]u8 = undefined;
    var grapheme_file_writer = grapheme_file.writer(io, &grapheme_file_buffer);
    const writer = &grapheme_file_writer.interface;
    var start = std.time.Timer.start() catch unreachable;

    const classes = comptime std.meta.fields(GraphemeBoundryClass);
    const states = comptime std.meta.fields(GraphemeBreakState);
    const total_states = states.len * classes.len * classes.len;

    try writer.print(
        \\//! DO NOT EDIT - This file is auto-generated by generate_lookup_tables.zig
        \\//!
        \\//! This file contains the lookup tables for the unicode grapheme break.
        \\
        \\const std = @import("std");
        \\
        \\const t = @import("types.zig");
        \\const GraphemeBreakTestResult = t.GraphemeBreakTestResult;
        \\const GraphemeBreakCombination = t.GraphemeBreakCombination;
        \\const GraphemeBreakState = t.GraphemeBreakState;
        \\const GraphemeBoundryClass = t.GraphemeBoundryClass;
        \\const getProperty = @import("properties.zig").getProperty;
        \\
        \\pub inline fn graphemeBreakClass(prev: GraphemeBoundryClass, next: GraphemeBoundryClass, state: *GraphemeBreakState) bool {{
        \\    const result = break_table[
        \\        (GraphemeBreakCombination{{
        \\            .state = state.*,
        \\            .gbc1 = prev,
        \\            .gbc2 = next,
        \\        }}).asUsize()
        \\    ];
        \\    state.* = result.state;
        \\    return result.is_break;
        \\}}
        \\
        \\pub inline fn graphemeBreak(prev_cp: u21, next_cp: u21, state: *GraphemeBreakState) bool {{
        \\    const result = break_table[
        \\        (GraphemeBreakCombination{{
        \\            .state = state.*,
        \\            .gbc1 = getProperty(prev_cp).grapheme_boundary_class,
        \\            .gbc2 = getProperty(next_cp).grapheme_boundary_class,
        \\        }}).asUsize()
        \\    ];
        \\    state.* = result.state;
        \\    return result.is_break;
        \\}}
        \\
        \\const break_table: [{d}]GraphemeBreakTestResult align(std.atomic.cache_line) = .{{
        \\
    , .{total_states});

    var i: usize = 0;

    @setEvalBranchQuota(50000);
    inline for (states) |initial_state| {
        inline for (classes) |gbc1| {
            inline for (classes) |gbc2| {
                var state: GraphemeBreakState = @field(GraphemeBreakState, initial_state.name);
                const combination: GraphemeBreakCombination = .{
                    .state = state,
                    .gbc1 = @field(GraphemeBoundryClass, gbc1.name),
                    .gbc2 = @field(GraphemeBoundryClass, gbc2.name),
                };
                const result = isGraphemeBreak(combination.gbc1, combination.gbc2, &state);
                assert(i == combination.asUsize());
                try writer.print("    // gbc1: {s}, gbc2: {s}, state: {s}\n", .{ gbc1.name, gbc2.name, initial_state.name });
                try writer.print("    .{{ .is_break = {any}, .state = .{t} }},\n", .{
                    result,
                    state,
                });
                i += 1;
            }
        }
    }

    try writer.writeAll("};\n\n");
    try writer.flush();

    return start.read();
}

// GB1 and GB2 are to be handled by the iterator
// GB3, GB4, and GB5 are to be handled by the caller. They must filter out the control characters.
// https://www.unicode.org/reports/tr29/
fn isGraphemeBreak(gbc1: GraphemeBoundryClass, gbc2: GraphemeBoundryClass, state: *GraphemeBreakState) bool {
    const current_state = state.*;
    if (current_state == .regional_indicator) {
        // NOTE(adi): GB12, GB13 if neither of the current or previous codepoints are RI then reset teh state
        if (gbc1 != .regional_indicator or gbc2 != .regional_indicator) {
            state.* = .default;
        }
    } else if (current_state == .extended_pictographic) {
        // NOTE(adi): If either of the codepoints dont have a valid class to continue an extended pictograph then reset the state
        if (!gbc1.isValidExtendedPictographic() or !gbc2.isValidExtendedPictographic()) {
            state.* = .default;
        }
    } else if (current_state == .InCB_consonant or current_state == .InCB_linker) {
        // NOTE(adi): If either of the codepoints is not a valid class to continue an indic sequence then reset the state
        if (!gbc1.isValidIndic() or !gbc2.isValidIndic()) {
            state.* = .default;
        }
    }
    // GB3: CR x LF
    // GB4: (Control | CR | LF) ÷
    // GB5: ÷ (Control | CR | LF)
    // These are handled by the iterator. Saves us from having to do it here and a smaller table

    // GB6 L×(L | V | LV | LVT)
    // GB7 (LV | V) × (V | T)
    // GB8 (LVT | T) × T
    switch (gbc1) {
        .L => switch (gbc2) {
            .L, .V, .LV, .LVT => return false,
            else => {},
        },
        .LV, .V => switch (gbc2) {
            .V, .T => return false,
            else => {},
        },
        .LVT, .T => switch (gbc2) {
            .T => return false,
            else => {},
        },
        else => {},
    }

    // GB9a x SpacingMark
    if (gbc2 == .spacing_mark) return false;
    // GB9b Prepend x
    if (gbc1 == .prepend) return false;

    // GB9c \p{InCB=Consonant} [ \p{InCB=Extend} \p{InCB=Linker} ]* \p{InCB=Linker} [ \p{InCB=Extend} \p{InCB=Linker} ]*× \p{InCB=Consonant}
    // ┌─────────────────┬─────────────┬───────────────────┬─────────────┐
    // │ Current State   │ See         │ New State         │ Break?      │
    // ├─────────────────┼─────────────┼───────────────────┼─────────────┤
    // │ *               │ Consonant   │ Consonant         │ (other rules│
    // │ Consonant       │ Extend      │ Consonant         │ no (GB9)    │
    // │ Consonant       │ Linker      │ ConsonantLinker   │ no (GB9)    │
    // │ ConsonantLinker │ Extend      │ ConsonantLinker   │ no (GB9)    │
    // │ ConsonantLinker │ Linker      │ ConsonantLinker   │ no (GB9)    │
    // │ ConsonantLinker │ Consonant   │ Consonant         │ NO (GB9c)   │
    // │ *               │ other       │ None              │ (other rules│
    // └─────────────────┴─────────────┴───────────────────┴─────────────┘
    if (gbc1 == .InCB_consonant) {
        if (gbc2.isIndicExtend()) {
            // row 2 of the table
            state.* = .InCB_consonant;
            return false;
        } else if (gbc2 == .InCB_linker) {
            // NOTE(adi): If we see a linker we just move straight to the linker state. Row 3 of table
            state.* = .InCB_linker;
            return false;
        } else {
            // NOTE(adi): If neither conditions are met then we continue. This is not an indic sequence.
        }
    } else if (state.* == .InCB_consonant) {
        if (gbc2 == .InCB_linker) {
            // Row 3 of table
            state.* = .InCB_linker;
            return false;
        } else if (gbc2.isIndicExtend()) {
            // Row 2 of table
            return false;
        } else {
            // Last row of table. We reset the state if we dont see something that exnteds the indic sequence
            state.* = .default;
        }
    } else if (state.* == .InCB_linker) {
        if (gbc2.isIndicExtend()) {
            // Row 4 of table
            return false;
        } else if (gbc2 == .InCB_linker) {
            // Row 5 of table
            return false;
        } else if (gbc2 == .InCB_consonant) {
            // Row 6 of table
            state.* = .InCB_consonant;
            return false;
        } else {
            // Last row of table. We reset the state if we dont see something that exnteds the indic sequence
            state.* = .default;
        }
    }

    // GB11 \p{Extended_Pictographic} Extend* ZWJ × \p{Extended_Pictographic}
    if (gbc1.isExtendedPictographic()) {
        // NOTE(adi): https://github.com/jacobsandlund/uucode/blob/5a3446d829feb7ce44c48fd905010b867d9934cd/src/x/grapheme.zig#L686
        if (gbc2.isExtention() or gbc2 == .zwj) {
            state.* = .extended_pictographic;
            return false;
        } else if (gbc1 == .emoji_modifier_base and gbc2 == .emoji_modifier) {
            state.* = .extended_pictographic;
            return false;
        } else {
            // NOTE(adi): Not valid GB11 sequence
        }
    } else if (state.* == .extended_pictographic) {
        if ((gbc1.isExtention() or gbc1 == .emoji_modifier) and (gbc2.isExtention() or gbc2 == .zwj)) {
            // We continue the cluster if we are in the middle of a sequence of extentions of zwj
            return false;
        } else if (gbc1 == .zwj and gbc2.isExtendedPictographic()) {
            // We are at the end of a sequence. This is still not a break but we are no longer extending a pictograph
            state.* = .default;
            return false;
        } else {
            // NOTE(adi): Not valid GB11 sequence
            state.* = .default;
        }
    }

    // GB12, GB13: Do not break within emoji flag sequences. That is, do not break between regional indicator (RI)
    // symbols if there is an odd number of RI characters before the break point.
    if (gbc1 == .regional_indicator and gbc2 == .regional_indicator) {
        if (state.* == .default) {
            state.* = .regional_indicator;
            return false;
        } else {
            state.* = .default;
            return true;
        }
    }

    // GB9: x (Extention | ZWJ). We handled most of the neuanced cases in the previous if statements
    if (gbc2.isExtention() or gbc1 == .zwj) {
        return false;
    }

    // Everrything else is a break
    return true;
}
