const std = @import("std");
const helpers = @import("helpers.zig");

const cut = helpers.cut;
const cutScalar = helpers.cutScalar;

pub fn main() !void {
    var threaded = std.Io.Threaded.init_single_threaded;
    const io = threaded.ioBasic();
    const file = try std.Io.Dir.cwd().createFile(io, "src/tools/types.zig", .{});
    defer file.close(io);

    var buffer: [4096]u8 = undefined;
    var file_writer = file.writer(io, &buffer);
    const writer = &file_writer.interface;
    try writer.writeAll(
        \\//! DO NOT EDIT - This file is auto-generated by print_structs.zig
        \\
        \\
    );

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    _ = arena.allocator().alloc(u8, 1 * 1024 * 1024) catch unreachable;
    _ = arena.reset(.retain_capacity);

    try printDerivedCorePropertiesStruct(io, arena.allocator(), writer);
    _ = arena.reset(.retain_capacity);

    try printEmojiStruct(io, arena.allocator(), writer);
    _ = arena.reset(.retain_capacity);

    try printGraphemeBreakEnum(io, arena.allocator(), writer);
    _ = arena.reset(.retain_capacity);

    try printEastAsianWidthEnum(io, arena.allocator(), writer);
    _ = arena.reset(.retain_capacity);

    try printGeneralCategoryEnum(io, arena.allocator(), writer);
}

pub fn printGeneralCategoryEnum(io: std.Io, allocator: std.mem.Allocator, writer: *std.Io.Writer) !void {
    var file = try std.Io.Dir.cwd().openFile(io, "UCD/extracted/DerivedGeneralCategory.txt", .{});
    defer file.close(io);
    var file_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &file_buffer);
    const reader = &file_reader.interface;
    var property_map = std.StringArrayHashMap(void).init(allocator);
    while (true) : (_ = try reader.discardDelimiterInclusive('\n')) {
        const first_byte = reader.peekByte() catch |err| switch (err) {
            error.EndOfStream => break,
            else => |e| return e,
        };
        if (first_byte == '\n') continue;
        if (first_byte == '#') continue;
        const line = try reader.takeDelimiterExclusive('#');
        _, var property = if (cutScalar(u8, line, ';')) |result| result else return error.InvalidLine;
        property = std.mem.trim(u8, property, " \t");
        if (property_map.get(property)) |_| {
            continue;
        } else {
            try property_map.putNoClobber(try allocator.dupe(u8, property), {});
        }
    }

    const count = property_map.count();
    try writer.print("pub const GeneralCategory = enum(u{d}) {{\n", .{std.math.log2_int_ceil(usize, count)});
    for (property_map.keys()) |key| {
        try writer.print("    {s},\n", .{key});
    }
    try writer.writeAll("};\n\n");
    try writer.flush();
}

pub fn printEastAsianWidthEnum(io: std.Io, allocator: std.mem.Allocator, writer: *std.Io.Writer) !void {
    var file = try std.Io.Dir.cwd().openFile(io, "UCD/extracted/DerivedEastAsianWidth.txt", .{});
    defer file.close(io);
    var file_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &file_buffer);
    const reader = &file_reader.interface;
    var property_map = std.StringArrayHashMap(void).init(allocator);
    while (true) : (_ = try reader.discardDelimiterInclusive('\n')) {
        const first_byte = reader.peekByte() catch |err| switch (err) {
            error.EndOfStream => break,
            else => |e| return e,
        };
        if (first_byte == '\n') continue;
        if (first_byte == '#') continue;
        const line = try reader.takeDelimiterExclusive('#');
        _, var property = if (cutScalar(u8, line, ';')) |result| result else return error.InvalidLine;
        property = std.mem.trim(u8, property, " \t");
        if (property_map.get(property)) |_| {
            continue;
        } else {
            try property_map.putNoClobber(try allocator.dupe(u8, property), {});
        }
    }

    const count = property_map.count();
    try writer.print("pub const EastAsianWidth = enum(u{d}) {{\n", .{std.math.log2_int_ceil(usize, count)});
    for (property_map.keys()) |key| {
        try writer.print("    {s},\n", .{key});
    }
    try writer.writeAll("};\n\n");
    try writer.flush();
}

pub fn printGraphemeBreakEnum(io: std.Io, allocator: std.mem.Allocator, writer: *std.Io.Writer) !void {
    var file = try std.Io.Dir.cwd().openFile(io, "UCD/auxiliary/GraphemeBreakProperty.txt", .{});
    defer file.close(io);
    var file_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &file_buffer);
    const reader = &file_reader.interface;
    var property_map = std.StringArrayHashMap(void).init(allocator);
    while (true) : (_ = try reader.discardDelimiterInclusive('\n')) {
        const first_byte = reader.peekByte() catch |err| switch (err) {
            error.EndOfStream => break,
            else => |e| return e,
        };
        if (first_byte == '\n') continue;
        if (first_byte == '#') {
            const missing = "# @missing:";
            const text = reader.peek(missing.len) catch |err| switch (err) {
                error.EndOfStream => break,
                else => |e| return e,
            };

            if (std.mem.eql(u8, text, missing)) {
                reader.toss(missing.len);
                const line = try reader.takeDelimiterExclusive('\n');
                _, var property = if (cutScalar(u8, line, ';')) |result| result else return error.InvalidMissingLine;
                property = std.mem.trim(u8, property, " \t");
                if (property_map.get(property)) |_| {
                    continue;
                } else {
                    try property_map.putNoClobber(try allocator.dupe(u8, property), {});
                }
            }
            continue;
        }
        const line = try reader.takeDelimiterExclusive('#');
        _, var property = if (cutScalar(u8, line, ';')) |result| result else return error.InvalidLine;
        property = std.mem.trim(u8, property, " \t");
        if (property_map.get(property)) |_| {
            continue;
        } else {
            try property_map.putNoClobber(try allocator.dupe(u8, property), {});
        }
    }

    const count = property_map.count();
    try writer.print("pub const GraphemeBreakProperty = enum(u{d}) {{\n", .{std.math.log2_int_ceil(usize, count)});
    for (property_map.keys()) |key| {
        try writer.print("    {s},\n", .{key});
    }
    try writer.writeAll("};\n\n");
    try writer.flush();
}

pub fn printEmojiStruct(io: std.Io, allocator: std.mem.Allocator, writer: *std.Io.Writer) !void {
    var file = try std.Io.Dir.cwd().openFile(io, "UCD/emoji/emoji-data.txt", .{});
    defer file.close(io);
    var file_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &file_buffer);
    const reader = &file_reader.interface;

    var property_map = std.StringArrayHashMap(void).init(allocator);
    while (true) : (_ = try reader.discardDelimiterInclusive('\n')) {
        const first_byte = reader.peekByte() catch |err| switch (err) {
            error.EndOfStream => break,
            else => |e| return e,
        };
        if (first_byte == '\n') continue;
        if (first_byte == '#') continue;
        const line = try reader.takeDelimiterExclusive('#');
        _, var property = if (cutScalar(u8, line, ';')) |result| result else return error.InvalidLine;
        property = std.mem.trim(u8, property, " \t");
        if (property_map.get(property)) |_| {
            continue;
        } else {
            try property_map.putNoClobber(try allocator.dupe(u8, property), {});
        }
    }
    const count = property_map.count();
    try writer.print("pub const EmojiBacking = u{d};\n\n", .{count});
    try writer.writeAll("pub const Emoji = packed struct(EmojiBacking) {\n");
    for (property_map.keys()) |key| {
        try writer.print("    {s}: bool = false,\n", .{key});
    }
    try writer.writeAll("};\n\n");
    try writer.writeAll("pub const EmojiMask = enum(EmojiBacking) {\n");
    for (property_map.keys(), 0..) |key, i| {
        try writer.print("    {s} = 0b{b},\n", .{ key, @as(usize, 1) << @intCast(i) });
    }
    try writer.writeAll("};\n\n");
    try writer.flush();
}

pub fn printDerivedCorePropertiesStruct(io: std.Io, allocator: std.mem.Allocator, writer: *std.Io.Writer) !void {
    var file = try std.Io.Dir.cwd().openFile(io, "UCD/DerivedCoreProperties.txt", .{});
    defer file.close(io);
    var file_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &file_buffer);
    const reader = &file_reader.interface;
    var property_map = std.StringArrayHashMap(void).init(allocator);
    var value_map = std.StringArrayHashMap(void).init(allocator);
    while (true) : (_ = try reader.discardDelimiterInclusive('\n')) {
        const first_byte = reader.peekByte() catch |err| switch (err) {
            error.EndOfStream => break,
            else => |e| return e,
        };
        if (first_byte == '\n') continue;
        if (first_byte == '#') {
            const search = "# Derived Property: ";
            var start = reader.peek(search.len) catch |err| switch (err) {
                error.EndOfStream => break,
                else => |e| return e,
            };
            if (std.mem.eql(u8, start, search)) {
                reader.toss(search.len);
                var property: []const u8 = try reader.takeDelimiterExclusive('\n');
                property = std.mem.trim(u8, property, " \t");
                property, _ = if (cutScalar(u8, property, ' ')) |result| result else .{ property, &.{} };
                property = std.mem.trim(u8, property, " \t()");
                if (std.mem.eql(u8, property, "Indic_Conjunct_Break")) {
                    property = "InCB";
                }
                try property_map.putNoClobber(try allocator.dupe(u8, property), {});
                continue;
            }
            const incb_value_str = "# Indic_Conjunct_Break=";
            start = reader.peek(incb_value_str.len) catch |err| switch (err) {
                error.EndOfStream => break,
                else => |e| return e,
            };
            if (std.mem.eql(u8, start, incb_value_str)) {
                reader.toss(incb_value_str.len);
                var property: []const u8 = try reader.takeDelimiterExclusive('\n');
                property = std.mem.trim(u8, property, " \t");
                try value_map.putNoClobber(try allocator.dupe(u8, property), {});
            }
        }
    }
    const count = property_map.count();
    const values_bits = std.math.log2_int_ceil(usize, value_map.count() + 1);
    try writer.print("pub const DerivedCorePropertiesBacking = u{d};\n\n", .{count + values_bits - 1});
    try writer.writeAll("pub const DerivedCoreProperties = packed struct(DerivedCorePropertiesBacking) {\n");
    for (property_map.keys()) |key| {
        if (std.mem.eql(u8, key, "InCB")) {
            try writer.print("    {s}: IndicConjunctBreakValue = .None,\n", .{key});
            continue;
        }
        try writer.print("    {s}: bool = false,\n", .{key});
    }
    try writer.writeAll("};\n\n");
    try writer.writeAll("pub const DerivedCorePropertiesMask = enum(DerivedCorePropertiesBacking) {\n");
    for (property_map.keys(), 0..) |key, i| {
        try writer.print("    {s} = 0b{b},\n", .{ key, @as(usize, 1) << @intCast(i) });
    }
    try writer.writeAll("};\n\n");
    try writer.print("pub const IndicConjunctBreakValue = enum(u{d}) {{\n", .{values_bits});
    try writer.writeAll("    None,\n");
    for (value_map.keys()) |key| {
        try writer.print("    {s},\n", .{key});
    }
    try writer.writeAll("};\n\n");
    try writer.flush();
}
