const std = @import("std");
const assert = std.debug.assert;

const helpers = @import("helpers.zig");
const t = @import("unicode_types.zig");
const u = @import("unicode_info.zig");
const UnicodeInfo = u.UnicodeInfo;
const Data = u.Data;
const parser = @import("parser.zig");

const export_types = @import("export/types.zig");
const Property = export_types.Property;
const GraphemeBoundryClass = export_types.GraphemeBoundryClass;
const max_codepoint = export_types.max_codepoint;
const zero_width_joiner = export_types.zero_width_joiner;
const zero_width_non_joiner = export_types.zero_width_non_joiner;

pub fn generatePropertyLookupTable(
    io: std.Io,
    allocator: std.mem.Allocator,
    file_path: []const u8,
    info: UnicodeInfo,
) !u64 {
    var start = std.time.Timer.start() catch unreachable;
    const property_file = try std.Io.Dir.cwd().createFile(io, file_path, .{});
    defer property_file.close(io);

    var property_file_buffer: [4096]u8 = undefined;
    var property_file_writer = property_file.writer(io, &property_file_buffer);
    const writer = &property_file_writer.interface;

    var stage1: std.ArrayList(u16) = .empty;
    var stage2: std.ArrayList(u16) = .empty;
    var stage3: std.ArrayList(Property) = .empty;
    defer {
        stage1.deinit(allocator);
        stage2.deinit(allocator);
        stage3.deinit(allocator);
    }

    const block_size = 256;
    const Block = [block_size]u16;

    var block: Block = undefined;
    var index_block: u16 = 0;

    var block_map = std.HashMap(Block, u16, struct {
        pub fn hash(_: @This(), b: Block) u64 {
            var hasher = std.hash.Wyhash.init(0);
            for (b) |id| {
                @call(.always_inline, std.hash.Wyhash.update, .{ &hasher, std.mem.asBytes(&id) });
            }
            return hasher.final();
        }
        pub fn eql(_: @This(), a: Block, b: Block) bool {
            return std.mem.eql(u16, &a, &b);
        }
    }, std.hash_map.default_max_load_percentage).init(allocator);

    for (0..std.math.maxInt(u21)) |cp| {
        const element: Property = if (cp >= max_codepoint) .invalid else getProperty(@truncate(cp), info.get(@truncate(cp)));

        const index_stage3 = std.mem.findScalar(Property, stage3.items, element) orelse blk: {
            const i = stage3.items.len;
            try stage3.append(allocator, element);
            break :blk i;
        };
        block[index_block] = std.math.cast(u16, index_stage3) orelse return error.Stage3Overflow;
        index_block += 1;

        // If we are in the last cp we need to commit the block
        if (index_block < block_size and cp != std.math.maxInt(u21)) continue;
        // clear out the remaining
        if (index_block < block_size) @memset(block[index_block..block_size], 0);

        const gop = try block_map.getOrPut(block);
        if (!gop.found_existing) {
            gop.value_ptr.* = std.math.cast(u16, stage2.items.len) orelse return error.Stage2Overflow;
            try stage2.appendSlice(allocator, block[0..index_block]);
        }

        try stage1.append(allocator, gop.value_ptr.*);
        index_block = 0;
    }

    std.debug.assert(stage1.items.len <= std.math.maxInt(u16));
    std.debug.assert(stage2.items.len <= std.math.maxInt(u16));
    std.debug.assert(stage3.items.len <= std.math.maxInt(u16));

    try writer.writeAll(
        \\//! DO NOT EDIT - This file is auto-generated by generate_lookup_tables.zig
        \\//! 
        \\//! This file contains the lookup tables for the unicode properties.
        \\//! 
        \\//! The tables are used by the unicode parsing code in `src/unicode/parse.zig`.
        \\ 
        \\const std = @import("std");
        \\
        \\const t = @import("types.zig");
        \\pub const Property = t.Property;
        \\pub const GraphemeBoundryClass = t.GraphemeBoundryClass;
        \\
        \\pub inline fn getProperty(cp: u21) Property {
        \\    if (cp > t.max_codepoint) unreachable;
        \\    const index_stage1 = cp >> 8;
        \\    const offset_stage2 = cp & 0xFF;
        \\    const index_stage2 = property_table.stage1[index_stage1] + offset_stage2;
        \\    return property_table.stage3[property_table.stage2[index_stage2]];
        \\}
        \\
        \\
    );

    try writer.print(
        \\const property_table = struct {{
        \\    pub const stage1: [{d}]u16 align(std.atomic.cache_line) = .{{
        \\        
    , .{stage1.items.len});

    for (stage1.items[0 .. stage1.items.len - 1], 0..) |item, i| {
        try writer.print("{d},", .{item});
        if (i % 32 == 31) try writer.print("{s}\n        ", .{if (i == 31) "//" else ""});
    }
    try writer.print("{d}\n    }};\n\n", .{stage1.items[stage1.items.len - 1]});

    try writer.print(
        \\    pub const stage2: [{d}]u16 align(std.atomic.cache_line) = .{{
        \\        
    , .{stage2.items.len});

    for (stage2.items[0 .. stage2.items.len - 1], 0..) |item, i| {
        try writer.print("{d},", .{item});
        if (i % 32 == 31) try writer.print("{s}\n        ", .{if (i == 31) "//" else ""});
    }
    try writer.print("{d}\n    }};\n\n", .{stage2.items[stage2.items.len - 1]});

    try writer.print(
        \\    pub const stage3: [{d}]Property align(std.atomic.cache_line) = .{{
        \\
    , .{stage3.items.len});

    for (stage3.items) |item| {
        try writer.print("        {f},\n", .{item});
    }
    try writer.writeAll("    };");

    try writer.writeAll("};\n\n");
    try writer.flush();

    return start.read();
}

// Reference:
// https://github.com/jacobsandlund/uucode/blob/ad6f8813b9163bfc93626ebbc0f1023e11c51de7/src/x/config_x/wcwidth.zig
fn getWidth(
    cp: u21,
    data: UnicodeInfo.Data,
) u2 {
    var width: u2 = 0;
    if (data.general_category == .Cc or // Other, Control
        data.general_category == .Cs or // Other, Surrogate
        data.general_category == .Zl or // Separator, Line
        data.general_category == .Zp) // Separator, Paragraph
    {
        width = 0;
    } else if (cp == 0x00AD0) { // Soft Hyphen
        width = 1;
    } else if (data.derived_core_properties.Default_Ignorable_Code_Point) {
        width = 0;
    } else if (cp == 0x2E3A) { // Two-Em Dash
        width = 2;
    } else if (cp == 0x2E3B) { // Three-Em Dash
        // NOTE: Treating it as 2 space since in terminals you cant render more than 2 spaces
        width = 2;
    } else if (data.east_asian_width == .W or data.east_asian_width == .F) {
        width = 2;
    } else if (data.grapheme_break == .Regional_Indicator) {
        width = 2;
    } else {
        width = 1;
    }

    const wcwidth_standalone = if (cp == 0x20E3) 2 else width;
    const wcwidth_zero_in_grapheme =
        if (width == 0 or
        data.emoji.Emoji_Modifier or
        data.derived_core_properties.Default_Ignorable_Code_Point or
        data.general_category == .Me or // Mark, Enclosing
        data.general_category == .Mn or // Mark, Non-Spacing
        data.grapheme_break == .V or
        data.grapheme_break == .T or
        data.grapheme_break == .Prepend)
            true
        else
            false;

    if (wcwidth_zero_in_grapheme and !data.emoji.Emoji_Modifier_Base) {
        return 0;
    } else {
        return wcwidth_standalone;
    }
}

pub fn getGraphemeBoundryClas(
    cp: u21,
    emoji: t.Emoji,
    props: t.DerivedCoreProperties,
    grapheme_break: t.GraphemeBreakProperty,
) GraphemeBoundryClass {
    if (emoji.Emoji_Modifier) {
        assert(grapheme_break == .Extend);
        assert(!emoji.Extended_Pictographic and emoji.Emoji_Component);
        return .emoji_modifier;
    } else if (emoji.Emoji_Modifier_Base) {
        assert(grapheme_break == .Other);
        assert(emoji.Extended_Pictographic);
        return .emoji_modifier_base;
    } else if (emoji.Extended_Pictographic) {
        assert(grapheme_break == .Other);
        return .extended_pictographic;
    } else {
        switch (props.InCB) {
            .None => {
                switch (grapheme_break) {
                    .Extend => {
                        if (cp == zero_width_non_joiner) return .zwnj else {
                            std.log.err("Invalid grapheme break 0x{x} with `Extend` GraphemeBreakProperty and None InCB", .{cp});
                            unreachable;
                        }
                    },
                    .CR, .LF, .Control, .Other => return .invalid,
                    .Prepend => return .prepend,
                    .Regional_Indicator => return .regional_indicator,
                    .SpacingMark => return .spacing_mark,
                    .L => return .L,
                    .V => return .V,
                    .T => return .T,
                    .LV => return .LV,
                    .LVT => return .LVT,
                    .ZWJ => return .zwj,
                }
            },
            .Extend => {
                if (cp == zero_width_joiner) {
                    assert(grapheme_break == .ZWJ);
                    return .zwj;
                } else {
                    assert(grapheme_break == .Extend);
                    return .InCB_extend;
                }
            },
            .Consonant => {
                assert(grapheme_break == .Other);
                return .InCB_consonant;
            },
            .Linker => {
                assert(grapheme_break == .Extend);
                return .InCB_linker;
            },
        }
    }
    unreachable;
}

pub fn getProperty(
    cp: u21,
    data: UnicodeInfo.Data,
) Property {
    assert(cp <= max_codepoint);
    return .{
        .width = getWidth(cp, data),
        .grapheme_boundary_class = getGraphemeBoundryClas(cp, data.emoji, data.derived_core_properties, data.grapheme_break),
    };
}
