//! DO NOT EDIT - This file is auto-generated by print_structs.zig

pub const DerivedCorePropertiesBacking = u21;

pub const DerivedCoreProperties = packed struct(DerivedCorePropertiesBacking) {
    Math: bool = false,
    Alphabetic: bool = false,
    Lowercase: bool = false,
    Uppercase: bool = false,
    Cased: bool = false,
    Case_Ignorable: bool = false,
    Changes_When_Lowercased: bool = false,
    Changes_When_Uppercased: bool = false,
    Changes_When_Titlecased: bool = false,
    Changes_When_Casefolded: bool = false,
    Changes_When_Casemapped: bool = false,
    ID_Start: bool = false,
    ID_Continue: bool = false,
    XID_Start: bool = false,
    XID_Continue: bool = false,
    Default_Ignorable_Code_Point: bool = false,
    Grapheme_Extend: bool = false,
    Grapheme_Base: bool = false,
    Grapheme_Link: bool = false,
    InCB: IndicConjunctBreakValue = .None,
};

pub const DerivedCorePropertiesMask = enum(DerivedCorePropertiesBacking) {
    Math = 0b1,
    Alphabetic = 0b10,
    Lowercase = 0b100,
    Uppercase = 0b1000,
    Cased = 0b10000,
    Case_Ignorable = 0b100000,
    Changes_When_Lowercased = 0b1000000,
    Changes_When_Uppercased = 0b10000000,
    Changes_When_Titlecased = 0b100000000,
    Changes_When_Casefolded = 0b1000000000,
    Changes_When_Casemapped = 0b10000000000,
    ID_Start = 0b100000000000,
    ID_Continue = 0b1000000000000,
    XID_Start = 0b10000000000000,
    XID_Continue = 0b100000000000000,
    Default_Ignorable_Code_Point = 0b1000000000000000,
    Grapheme_Extend = 0b10000000000000000,
    Grapheme_Base = 0b100000000000000000,
    Grapheme_Link = 0b1000000000000000000,
    InCB = 0b10000000000000000000,
};

pub const IndicConjunctBreakValue = enum(u2) {
    None,
    Linker,
    Consonant,
    Extend,
};

pub const EmojiBacking = u6;

pub const Emoji = packed struct(EmojiBacking) {
    Emoji: bool = false,
    Emoji_Presentation: bool = false,
    Emoji_Modifier: bool = false,
    Emoji_Modifier_Base: bool = false,
    Emoji_Component: bool = false,
    Extended_Pictographic: bool = false,
};

pub const EmojiMask = enum(EmojiBacking) {
    Emoji = 0b1,
    Emoji_Presentation = 0b10,
    Emoji_Modifier = 0b100,
    Emoji_Modifier_Base = 0b1000,
    Emoji_Component = 0b10000,
    Extended_Pictographic = 0b100000,
};

pub const GraphemeBreakProperty = enum(u4) {
    Other,
    Prepend,
    CR,
    LF,
    Control,
    Extend,
    Regional_Indicator,
    SpacingMark,
    L,
    V,
    T,
    LV,
    LVT,
    ZWJ,
};

pub const EastAsianWidth = enum(u3) {
    N,
    A,
    H,
    W,
    F,
    Na,
};

pub const GeneralCategory = enum(u5) {
    Cn,
    Lu,
    Ll,
    Lt,
    Lm,
    Lo,
    Mn,
    Me,
    Mc,
    Nd,
    Nl,
    No,
    Zs,
    Zl,
    Zp,
    Cc,
    Cf,
    Co,
    Cs,
    Pd,
    Ps,
    Pe,
    Pc,
    Po,
    Sm,
    Sc,
    Sk,
    So,
    Pi,
    Pf,
};
